name: build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/updatecli.yml"
      - ".github/workflows/release.yml"
      - ".github/workflows/dependabot-merge.yml"
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: "temurin"
          java-version: "11"
          check-latest: false
      - name: Install Just
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: casey/just
      - name: Install Maven Cleanup Tool
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: hpehl/mcup
      - name: Maven RO Cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: github.event_name == 'pull_request'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('Justfile') }}-${{ hashFiles('.env') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-${{ hashFiles('Justfile') }}
            ${{ runner.os }}-maven-cache-
      - name: Maven RW Cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: github.event_name != 'pull_request'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('Justfile') }}-${{ hashFiles('.env') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-${{ hashFiles('Justfile') }}
            ${{ runner.os }}-maven-cache-
      - name: Build & Test
        run: |
          just build test
          mcup --versions '3..' keep
