name: makefile

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/updatecli.yml"
      - ".github/workflows/release.yml"
      - ".github/workflows/dependabot-merge.yml"
      - ".github/workflows/makefile.yml"
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: "temurin"
          java-version: "11"
          check-latest: false
      ## Since we're wrapping maven there is no pom file which
      ## means that setup-java fails if you add a cache: "maven"
      - name: Maven Cache
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-
      - name: Build & Test
        run: |
          make build test
