# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: updatecli
on:
  workflow_dispatch:
  schedule:
    - cron: "15 03 * * SUN"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  updatecli:
    name: Run updatecli
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: "Create Token"
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.WORKFLOW_UPDATE_CLIENT_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"
      - name: updatecli
        uses: quotidian-ennui/actions-olio/default-updatecli@528d118cf867515584403396edee8a564a23bc00 # v1.3.0
        with:
          token: ${{ steps.app-token.outputs.token }}
