# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: updatecli
on:
  workflow_dispatch:
  schedule:
    - cron: "15 03 * * SUN"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  updatecli:
    name: Run updatecli
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Create Token"
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"
      - name: updatecli
        uses: quotidian-ennui/actions-olio/default-updatecli@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          token: ${{ steps.app-token.outputs.token }}
